- src/lib/ui/sync-factory.js
@alexpsi sometimes the Get Translations button does not get activated even if resource has completed languages. Can you pls review and merge?
> Fix js-can-download

- src/app.js
- src/lib/common.js
- src/lib/io.js
- src/lib/syncUtil.js
- src/lib/transifex-api/project.js
- src/lib/transifex-api/resource.js
- src/lib/ui/sync-dynamic-content.js
- src/lib/ui/sync-factory.js
- src/lib/zendesk-api/config.js
- src/lib/zendesk-api/dynamic-content.js
- src/lib/zendesk-api/factory.js
- src/lib/zendesk-api/pagination.js
- src/templates/loading_page.hdbs
- src/templates/sync_page.hdbs
- test/unit/01.txproject.spec.js
@alexpsi if you have the time take a look at this PR. It has a bit of refactoring  in order to support dynamic content as well, which has a bit different api endpoints.
> Dynamic content

- src/lib/ui/sync-factory.js
@SofiaMargariti  @samuelchan22 found a bug in search where if you are on page 2 and try to search, its calling the api with page=2 and not showing any results. So i tried to reset the page to 1 every time someone queries for a new string.
> Fixing Search bug

- src/lib/transifex-api/project.js
- src/lib/ui/sync-factory.js
- src/templates/loading_page.hdbs
@alexpsi pls review and merge!
> Error message when zendesk integration is not supported by plan

- src/templates/loading_page.hdbs
- src/templates/sync_page.hdbs
@alexpsi pls review and merge! I did a test with ~90 resources and ~130 languages and it worked fine.
> Increase page size

- src/lib/zendesk-api/factory.js
- src/manifest.json
Jira issue: https://transifex.atlassian.net/browse/TX-7927
> Correctly select the default brand

- src/app.js
- src/lib/io.js
- src/lib/txUtil.js
- src/lib/zendesk-api/factory.js
- src/manifest.json
@alexpsi this PR fixes two things:
* adds basic auth to all requests that access resources that might have restricted access.
* makes the trailing slash in the settings' project url optional.
Pls review and merge.
> Resources with restricted access

- src/lib/ui/sync-factory.js
Fix the following bugs:
* Refresh data when the app is focused, so it is always up-to-date with any content changes
* Correctly handle failed requests on dynamic content page
* Fix a bug on dynamic content page that occurred when no data were received
> Fix various bugs

- src/javascripts/ui/sync-factory.js
- src/stylesheets/utilities.scss
- src/templates/loading_page.hdbs
* Preserve the same header height on loading pages
* Remove unused event handling
> Fix two minor bugs

- dist/manifest.json
> Bump version to 3.0.1

- dist/manifest.json
- package.json
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
Send information about failed requests to Sentry
> Report failed requests to sentry

- package-lock.json
- src/javascripts/transifex-api/resource.js
- src/javascripts/zendesk-api/dynamic-content.js
- src/javascripts/zendesk-api/factory.js
------------------------
Reported issue: 
Bulk mode dynamic content download did not work properly.
There were missing some code lines responsible for the iteration on dynamic content when the bulk mode was required.
How to test
-----------
Navigate to Zendesk and sign in.
Got the right top of the page to open the help desk.
Add transifex support plugin through the gear icon --> manage ...
Create some dynamic content and then do move on sending the content to transifex throughout the tx installed application 
For the code:
For the PR:
Dynamic content used not to sync in bulk mode. Thus we added a couple of code lines that used to be missing.
> TX-11047: Fix the bulk mode dynamic content download

- dist/manifest.json
- package.json
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
APP is going to be released.
Bumping APP version to release.
How to test
-----------
Code:
PR:
> Bump APP version

- dist/manifest.json
- package.json
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
- src/javascripts/zendesk-api/factory.js
How to test
-----------
Code:
PR:
> Search all locales instead

- dist/manifest.json
- package.json
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
- src/javascripts/zendesk-api/factory.js
Bringing master in line with devel
How to test
-----------
Code:
PR:
> Bringing master in line with devel

- src/javascripts/syncUtil.js
- src/javascripts/zendesk-api/factory.js
The problem is that when updating article translations
multiple requests to zendesk api are created in parallel
and at some point the zendesk service could respond
with error 503 or similar (too busy)
The solution given is to apply a retries mechanism in order
to call the failed request at some other point in time which
could lead to a successful response.
The mechanism is a backoff retry with jitter.
The number of retries is 5 per request.
How to test
-----------
Please setup a local environment and use it to generate article translations
with local server/db.
Code:
PR:
> Article translations with retries

- dist/manifest.json
- package.json
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
Bump version
How to test
-----------
Code:
PR:
> Bump version

- src/javascripts/syncUtil.js
- src/javascripts/zendesk-api/factory.js
Added more retries (from 5 to 10) and more timeout (from 10 to 30 secs).
Fixed the call to promise function, seems that the call was not working correctly
How to test
-----------
Code:
PR:
> Zendesk retries fix and fine tuning

- dist/manifest.json
- package.json
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
How to test
-----------
Code:
PR:
> Bump version to 3.0.11

- dist/manifest.json
- package.json
- src/javascripts/syncUtil.js
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
- src/javascripts/zendesk-api/config.js
- src/javascripts/zendesk-api/factory.js
Align master with devel no version bump to bypass zendesk approval operation,.
How to test
-----------
Code:
PR:
> Align devel and master branches

- src/javascripts/io.js
- src/javascripts/zendesk-api/config.js
Fix for the dynamic content page by merging locales + extra locales
How to test
-----------
Code:
PR:
> Fixes the dynamic content page

- PULL_REQUEST_TEMPLATE.md
- dist/manifest.json
- package-lock.json
- package.json
- src/javascripts/transifex-api/project.js
- src/javascripts/transifex-api/resource.js
- src/javascripts/zendesk-api/config.js
- src/javascripts/zendesk-api/dynamic-content.js
- src/javascripts/zendesk-api/factory.js
How to test
-----------
Code:
PR:
> Align with devel branch
